spring:
  neo4j:
    uri: bolt://101.43.113.43:7687
    authentication:
      username: neo4j
      password: Neo4j
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    mongodb:
      uri: mongodb://BI:secret@42.192.1.101:27017/mydb